### ISSUE TITLE
CODE REVIEW

### ISSUE THREAD

**Issue by BaharaJr** [Marygoreth/HD#1]
I love the way you aligned your code, that is some good improvement. However, one thing you should never do unless you want to drop a nuclear bomb on earth is that never place your navigation into the head tags. Navigation goes into the header, not head.

Otherwise, I love the improvement.

Useful resources 
[Differences between head and header](https://stackoverflow.com/questions/33919706/what-is-the-real-difference-between-the-head-and-header-tag)

[what is the difference between head and header again? and what goes inside each?](https://teamtreehouse.com/community/what-is-the-different-between-head-and-header-again-and-what-goes-inside-each)

**Comment by Marygoreth** [comment]
noted.......thank you
